language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean  #清除
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "luoyunchong" # 修改name
  - git config user.email "luoyunchong@foxmail.com" # 修改email
  - git add .
  - git commit -m "Travis CI Auto Builder"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称
# E: Build LifeCycle


branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/luoyunchong/luoyunchong.github.io.git


notifications:
  email:
    - luoyunchong@foxmail.com
  on_success: change
  on_failure: always