language: node_js
node_js: stable

cache:
    apt: true
    directories:
        - node_modules # 缓存不经常更改的内容

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo clean  #清除
  - hexo g

after_script:
  # - cd ./public
  # - git init
  # - git config user.name "luoyunchong" # 修改name
  # - git config user.email "luoyunchong@foxmail.com" # 修改email
  # - git add .
  # - git commit -m "Travis CI Auto Builder"
  # - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master # GH_TOKEN是在Travis中配置token的名称
  - git config user.name "luoyunchong" # 修改name
  - git config user.email "luoyunchong@foxmail.com" # 修改email
  - sed -i "s/gh_token/${GH_TOKEN}/g" ./_config.yml
  - hexo deploy

# after_success:
#   - openssl aes-256-cbc -K $encrypted_2c430460807a_key -iv $encrypted_2c430460807a_iv
#   - in id_rsa.enc -out ~\/.ssh/id_rsa -d
#   - rsync -az --delete ./public/* ubuntu@122.152.192.161:/var/www/html/hexo-blog

branches:
  only:
    - master
env:
 global:
   - GH_REF: github.com/luoyunchong/luoyunchong.github.io.git


notifications:
  email:
    - luoyunchong@foxmail.com
  on_success: change
  on_failure: always